const mockData = [

  {
    symbol: 'AAPL',
    companyName: 'Apple Inc.',
    marketCap: 2599680475136,
    sector: 'Technology',
    industry: 'Consumer Electronics',
    beta: 1.1855,
    price: 159.3000,
    lastAnnualDividend: 0.8800,
    volume: 97489357,
    exchange: 'Nasdaq Global Select',
    exchangeShortName: 'NASDAQ',
    country: 'US',
    isEtf: false,
    isActivelyTrading: true,
  },
  {
    symbol: 'NVDA',
    companyName: 'NVIDIA Corporation',
    marketCap: 532091863040,
    sector: 'Technology',
    industry: 'Semiconductors',
    beta: 1.4114,
    price: 213.5200,
    lastAnnualDividend: 0.2400,
    volume: 52118150,
    exchange: 'Nasdaq Global Select',
    exchangeShortName: 'NASDAQ',
    country: 'US',
    isEtf: false,
    isActivelyTrading: true,
  },
  {
    symbol: 'AVGO',
    companyName: 'Farid.inc',
    marketCap: 233766141952,
    sector: 'Technology',
    industry: 'Semiconductors',
    beta: 1.0192,
    price: 570.7000,
    lastAnnualDividend: 14.9000,
    volume: 2821015,
    exchange: 'Nasdaq Global Select',
    exchangeShortName: 'NASDAQ',
    country: 'US',
    isEtf: false,
    isActivelyTrading: true,
  },
];

export default mockData;
